### ISSUE TITLE
Make history persist in neovim sessions

### ISSUE THREAD

**Issue by j-xella** [VoxelPrismatic/rabbit.nvim#13]
Rabbit is basically `#` on steroids :)

But the alternative buffer can be automatically stored in vim sessions and then loaded back. It would be nice to have such possibility (switchable, if possible) in rabbit as well.

**Comment by VoxelPrismatic** [comment]
Rabbit Oxide stores your most frequently accessed files (in the current directory)

Rabbit Harpoon allows you to make a custom workspace listing in the current directory.

You can scroll down when Rabbit is open to view keybinds
