### ISSUE TITLE
Possibility to add a folder to harpoon

### ISSUE THREAD

**Issue by j-xella** [VoxelPrismatic/rabbit.nvim#14]
Maybe I am missing something, but is there a way to add not a file, but a folder to harpoon?

When such entry is clicked, it would be like `e folder_name`

**Comment by j-xella** [comment]
Sorry, I hope I am not misunderstanding the situation, but in this ticket I meant not the way to organise entries in Rabbit lists, but actually being able to add filesystem folder names to various Rabbit lists, same as adding file names. 

vim/nvim can "open" folders like files, in which case file explorer plugin is launched. Sometimes I have a folder with some files which I edit often. However, I don't want all those files in harpoon. Maybe because there are too many of them, they will make the list unmanageable. Maybe because old files often get removed and new files added. All I want is to be able quickly open a folder, so that I could easily select from what is in it.

**Comment by VoxelPrismatic** [comment]
I think what you're looking for in this example is a plugin like Oil. I love this and use it myself.

https://github.com/stevearc/oil.nvim
