### ISSUE TITLE
Installing with Packer?

### ISSUE THREAD

**Issue by fakeharxy** [VoxelPrismatic/rabbit.nvim#4]
Hello, I'm trying everything to get this installed (neovim, mac, packer), my setup looks like this:

```
  use { "voxelprismatic/rabbit.nvim",
    config = function()
      require('rabbit').setup()
    end,
}
```

and I'm getting an error message: `packer.nvim: error running config for rabbit.nvim: ... defaults.lua:50: bad argument #2 to 'grab_color' (number expected, got nil)`

Any thoughts? I haven't setup any config obvs as I assume it will use defaults. Thanks.

**Comment by VoxelPrismatic** [comment]
That's on me!

Basically, I tried to pull whatever default colors you use, but if you have no foreground color set for, say, the Normal highlight group, it'll crash.

I just fixed it in this latest release, please try again and let me know how it goes.
